clear;
clc;

x = 1:12;
[num] = xlsread('I_rms');
I1 = num(:,1);
I2 = num(:,2);
I3 = num(:,3);
I_A_err_1 = (I1 - I3)./I3;
I_A_err_2 = (I2 - I3)./I3;
I_A_div_1 = I1./I3;
I_A_div_2 = I2./I3;
figure(1);
subplot(2,2,1);
plot(x,I_A_div_1);
ylabel('A相电流样机与标准值比值');
subplot(2,2,2);
plot(x,I_A_div_2);
ylabel('A相电流致远与标准值比值');
subplot(2,2,3);
plot(x,I_A_err_1);
ylabel('A相电流样机误差');
subplot(2,2,4);
plot(x,I_A_err_2);
ylabel('A相电流致远误差');

I4 = num(:,4);
I5 = num(:,5);
I6 = num(:,6);
I_B_err_1 = (I4 - I6)./I6;
I_B_err_2 = (I5 - I6)./I6;
I_B_div_1 = I4./I6;
I_B_div_2 = I5./I6;
figure(2);
subplot(2,2,1);
plot(x,I_B_div_1);
ylabel('B相电流样机与标准值比值');
subplot(2,2,2);
plot(x,I_B_div_2);
ylabel('B相电流致远与标准值比值');
subplot(2,2,3);
plot(x,I_B_err_1);
ylabel('B相电流样机误差');
subplot(2,2,4);
plot(x,I_B_err_2);
ylabel('B相电流致远误差');

I7 = num(:,7);
I8 = num(:,8);
I9 = num(:,9);
I_C_err_1 = (I7 - I9)./I9;
I_C_err_2 = (I8 - I9)./I9;
I_C_div_1 = I7./I9;
I_C_div_2 = I8./I9;
figure(3);
subplot(2,2,1);
plot(x,I_C_div_1);
ylabel('C相电流样机与标准值比值');
subplot(2,2,2);
plot(x,I_C_div_2);
ylabel('C相电流致远与标准值比值');
subplot(2,2,3);
plot(x,I_C_err_1);
ylabel('C相电流样机误差');
subplot(2,2,4);
plot(x,I_C_err_2);
ylabel('C相电流致远误差');

M = [I_A_err_1 I_A_err_2 I_A_div_1 I_A_div_2 I_B_err_1 I_B_err_2 I_B_div_1 I_B_div_2 I_C_err_1 I_C_err_2 I_C_div_1 I_C_div_2];
xlswrite('I.xls',M);